### ISSUE TITLE
Numeric value (4294967295) out of range of int exception when using execInContainer

### ISSUE THREAD

**Issue by ncoif-tw** [testcontainers/testcontainers-java#2070]
I'm using testcontainers version `1.12.3` to spin up a redis instance and run some integrations tests; my test setup is similar to the following:

```
import org.junit.Test;
import org.junit.rules.ExternalResource;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy;

public class Test extends ExternalResource {
    private GenericContainer redis;

    @Override
    protected void before() {
      redis = new GenericContainer("redis:5.0.3");
      redis.start();
      redis.waitingFor(new LogMessageWaitStrategy().withRegEx(".*Ready to accept connections.*"));
      servers.values().forEach(WireMockServer::start);
    }

    // multiple tests that are using this redis container
    @Test
    public void test() {
    
    }
    
    @Override
    protected void after() {
      try {
          int cleanupRedisExitCode = redis.execInContainer("redis-cli", "FLUSHALL").getExitCode();
          assertThat(cleanupRedisExitCode).isEqualTo(0);
      } catch (Exception e) {
          throw new IllegalStateException("Unable to cleanup the redis container", e);
      }
      servers.values().forEach(WireMockServer::resetAll);
    }
}

```
I'm getting the following exception:

```
java.lang.IllegalStateException: Unable to cleanup the redis container
Caused by: org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException: 
Numeric value (4294967295) out of range of int
 at [Source: (org.testcontainers.shaded.okio.RealBufferedSource$1); line: 1, column: 377] (through reference chain: com.github.dockerjava.api.command.InspectExecResponse["Pid"])
Caused by: org.testcontainers.shaded.com.fasterxml.jackson.core.JsonParseException: 
Numeric value (4294967295) out of range of int
 at [Source: (org.testcontainers.shaded.okio.RealBufferedSource$1); line: 1, column: 387]
```

When putting a breakpoint in the `after` method of my tests, I can observe that the redis container is up, and I can successfully execute the command, which returns OK:

`docker exec -ti 9c196d648191 bash -c 'redis-cli FLUSHALL'`

My docker version is the following:

```
docker version
Client:
 Version:           19.03.4-ce
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        9013bf583a
 Built:             Sat Oct 19 04:40:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.4-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       9013bf583a
  Built:            Sat Oct 19 04:39:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

From my understanding, it's a problem with the docker-java api, that fails to find the PID in the response, when executing the command. This exception seems to be environment-specific (it's not consistently reproducible, and seems more reliable on some other computers), but I'm not really sure to know where to start investigating.

Any ideas/pointers on what to do?

**Comment by pazepaze** [comment]
I have a similar issue. To me it looks like this issue would already be fixed in docker-java since version 3.2.0-rc2 with this [issue](https://github.com/docker-java/docker-java/issues/1259).

**Comment by bsideup** [comment]
Yes, we're working on releasing docker-java 3.2.0, and, meanwhile, track the integration here:
https://github.com/testcontainers/testcontainers-java/pull/2297

You can use Jitpack to try the version from that branch

**Comment by codablock** [comment]
I'm having the same issue and tried #2297 through Jitpack. I'm getting lots of exceptions like these:
```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/testcontainers/shaded/com/sun/jna/LastErrorException
        at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
        at org.rnorth.ducttape.timeouts.Timeouts.getWithTimeout(Timeouts.java:43)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:40)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.ping(DockerClientProviderStrategy.java:182)
        at org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy.test(EnvironmentAndSystemPropertyClientProviderStrategy.java:41)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$2(DockerClientProviderStrategy.java:118)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
        at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:154)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:113)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:134)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.listImagesCmd(LazyDockerClient.java:12)
        at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68)
        at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32)
        at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18)
        at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:62)
        at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:25)
        at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
        at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
        at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1263)
        at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:600)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:311)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
        at net.hellmann.cit.common.messaging.spring.kafka.ContainerSupport.startKafka(ContainerSupport.java:25)
        at net.hellmann.cit.common.messaging.spring.kafka.KafkaMessageBusTest.startKafka(KafkaMessageBusTest.java:64)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllMethods$8(ClassTestDescriptor.java:373)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllMethods(ClassTestDescriptor.java:372)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:201)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:74)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:102)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.NoClassDefFoundError: org/testcontainers/shaded/com/sun/jna/LastErrorException
        at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixSocketFactory.createSocket(UnixSocketFactory.java:24)
        at org.testcontainers.shaded.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:257)
        at org.testcontainers.shaded.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at org.testcontainers.shaded.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at org.testcontainers.shaded.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at org.testcontainers.shaded.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at org.testcontainers.shaded.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.testcontainers.shaded.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at org.testcontainers.shaded.okhttp3.RealCall.execute(RealCall.java:81)
        at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:276)
        at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
        at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkHttpInvocationBuilder.get(OkHttpInvocationBuilder.java:239)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.PingCmdExec.execute(PingCmdExec.java:26)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.PingCmdExec.execute(PingCmdExec.java:12)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$null$4(DockerClientProviderStrategy.java:185)
        at org.rnorth.ducttape.ratelimits.RateLimiter.getWhenReady(RateLimiter.java:51)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$ping$5(DockerClientProviderStrategy.java:183)
        at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: org.testcontainers.shaded.com.sun.jna.LastErrorException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by orelgenya** [comment]
The Jitpack solution solved the issue for me in GitLab DinD.

**Comment by bsideup** [comment]
@codablock the `ClassNotFoundException` should be fixed in #2297 now, could you please try?

**Comment by the-bug** [comment]
Jitpack solved it for me as well. @bsideup Thanks!
How is https://github.com/testcontainers/testcontainers-java/pull/2297 doing?

**Comment by rnorth** [comment]
The fix, #2297, was released in 1.14.0, so I'll close.
