### ISSUE TITLE
1.16.1 fails for Selenium 4.0.0 and Chrome browser

### ISSUE THREAD

**Issue by tobiasstadler** [testcontainers/testcontainers-java#4593]
I am using Selenium 4.0.0 with Chrome as web browser. When I upgrade testcontainers to 1.16.1 I get the following error:
```
java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chrome/ChromeOptions;
		at org.testcontainers.containers.BrowserWebDriverContainer.configure(BrowserWebDriverContainer.java:173)
		at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:322)
		at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
```

The error does not exist on 1.16.0.

**Comment by tobiasstadler** [comment]
You probably need #4580. Just add `waitingFor(Wait.forLogMessage(".*Started Selenium Standalone.*", 1))` to your container.

**Comment by orange-buffalo** [comment]
Same here with `1.16.2` and Selenide `6.x` (Selenium `4.x`). 

Do you guys need any help with resolving this?

**Comment by kiview** [comment]
@orange-buffalo thanks for offering your help. If you like, you can review this PR (https://github.com/testcontainers/testcontainers-java/pull/4842) and also check if it resolves it for you by using the [Jitpack version](https://www.testcontainers.org/jitpack_dependencies/).

**Comment by orange-buffalo** [comment]
I've tested #4609 and it works smoothly.
