### ISSUE TITLE
Problem with shaded dependencies after upgrade from 1.6.0 to 1.7.1

### ISSUE THREAD

**Issue by eksd** [testcontainers/testcontainers-java#656]
Hi! I've just upgraded my testcontainers for postgres from 1.6.0 to 1.7.1 and there is problem with resolving commons-io and commons-lang dependencies wich are required in testcontainers.
They are shaded in build.gradle of testcontainers, so I have:

`Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
        at org.testcontainers.jdbc.ContainerDatabaseDriver.runInitScriptIfRequired(ContainerDatabaseDriver.java:234)
        at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:158)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
`

If I add these deps in my pom, problem is solved.
 
Why are these deps shaded?

**Comment by hartmut-nex** [comment]
thx, run into the same issue

**Comment by bsideup** [comment]
Released as 1.7.3
