### ISSUE TITLE
[Bug]: Error after updating to kafka 1.19.8 from 1.19.1 

### ISSUE THREAD

**Issue by harry9656** [testcontainers/testcontainers-java#8757]
### Module

Kafka

### Testcontainers version

1.19.8

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

ARM

### Docker version

```shell
26.0.0
```

### What happened?

I tried to upgrade the kafka testcontainer from 1.19.1 to 1.19.8 in a Spring boot 3 application written in Java 17.
The test compiles and runs fine with version 1.19.1. But after the upgrade, it throws NoClassDefFoundError.

```Java
@Testcontainers
@SpringBootTest(classes = KafkaApplication.class)
class KafkaIntegrationTest {

    @Container
    private static final KafkaContainer KAFKA = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:latest"));
    // Failing in the line above.
}
```

### Relevant log output

```shell
java.lang.NoClassDefFoundError: org/testcontainers/containers/ContainerDef
        at com.spring.kafka.delay.KafkaIntegrationTest.<clinit>(KafkaIntegrationTest.java:36)
```

**Comment by eddumelendez** [comment]
Please, make sure all your testcontainers dependencies have the same version. I highly recommend using the bom.
