### ISSUE TITLE
Missing pom with v1.16.3

### ISSUE THREAD

**Issue by croudet** [testcontainers/testcontainers-java#4945]
When upgrading to v1.16.3, I got this warning:
`[WARNING] The POM for org.testcontainers:testcontainers:jar:1.16.3 is missing, no dependency information available`

which leads to compilation error:
```
[ERROR] ....[42,13] cannot access org.junit.rules.TestRule
[ERROR]   class file for org.junit.rules.TestRule not found
```

**Comment by bsideup** [comment]
Seems to be there:
https://repo1.maven.org/maven2/org/testcontainers/testcontainers/1.16.3/testcontainers-1.16.3.pom

**Comment by croudet** [comment]
It does not show here: https://search.maven.org/artifact/org.testcontainers/testcontainers/1.16.3/jar

and shows here https://search.maven.org/artifact/org.testcontainers/testcontainers/1.16.2/jar

**Comment by bsideup** [comment]
maybe it is a problem with search.maven.org then?

https://repo1.maven.org is **the** repo from where the artifacts are downloaded and the file is deployed to it. Maybe search.maven.org cached some wrong state?

**Comment by kiview** [comment]
@croudet Maven search indexes and sites always need some additional time to sync up after a new release, this is expected.
