### ISSUE TITLE
UnixSocketClientProviderStrategy cannot be instantiated because class JsonMerge is not found

### ISSUE THREAD

**Issue by tensberg** [testcontainers/testcontainers-java#3295]
After I updated Testcontainers from 1.10.6 to 1.15.0-rc2, the `UnixSocketClientProviderStrategy` fails to load because of a `Root cause ClassNotFoundException (com.fasterxml.jackson.annotation.JsonMerge)`:

    DEBUG ....DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception NoClassDefFoundError (com/fasterxml/jackson/annotation/JsonMerge). Root cause ClassNotFoundException (com.fasterxml.jackson.annotation.JsonMerge)
    INFO ....DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/usr/local/opt/postgresql@10/bin, /Users/koch/.jenv/bin, /usr/local/opt/node@8/bin, /usr/local/sbin, /Users/koch/.nvm/versions/node/v12.18.3/bin, /Users/koch/.sdkman/candidates/visualvm/current/bin, /Users/koch/.sdkman/candidates/maven/current/bin, /Users/koch/.sdkman/candidates/java/current/bin, /Users/koch/.sdkman/candidates/gradle/current/bin, /usr/local/bin, /usr/bin, /bin, /usr/sbin, /sbin, /usr/local/MacGPG2/bin, /Users/koch/.krew/bin, /Users/koch/bin, /Users/koch/Library/Python/2.7/bin, /Users/koch/Library/Android/sdk/tools, /Users/koch/Library/Android/sdk/tools/bin, /Users/koch/Library/Android/sdk/platform-tools, /Users/koch/.gem/ruby/2.0.0/bin])
    DEBUG ....DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception NoClassDefFoundError (Could not initialize class org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder)
    ERROR ....DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
    ERROR ....DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception NoClassDefFoundError (com/fasterxml/jackson/annotation/JsonMerge). Root cause ClassNotFoundException (com.fasterxml.jackson.annotation.JsonMerge)
    ERROR ....DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception NoClassDefFoundError (Could not initialize class org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder)

Apparently the strategy does not use the shaded jackson-annotations library.

Our project uses the old version 2.8.0 of jackson-annotations, which does not include `JsonMerge`. Updating jackson-annotations to a later version fixes Testcontainers startup, but causes problems elsewhere (unrelated to Testcontainers).

Tested on MacOS 10.15.6 with Docker Desktop 2.4.0.0.

**Comment by bsideup** [comment]
> Updating jackson-annotations to a later version fixes Testcontainers startup, but causes problems elsewhere (unrelated to Testcontainers).

Testcontainers depends on `docker-java` which depends on `jackson-annotations` version that includes `JsonMerge`.
Since updating the dependency seems to fix the problem, this does not sound like Testcontainers' issue, so I will close it.

**Comment by tensberg** [comment]
Thanks for the fast response. Is it intentional that Testcontainers now depends on `docker-java`? Because the testcontainers.org homepage states this:

> Testcontainers uses the docker-java client library, which in turn depends on JAX-RS, Jersey and Jackson libraries. These libraries in particular seem to be especially prone to conflicts with test code/application under test code. As such, these libraries are 'shaded' into the core testcontainers JAR and relocated under org.testcontainers.shaded to prevent class conflicts.

**Comment by bsideup** [comment]
@tensberg it always has been depending on `docker-java`, just we were including it into our jar (due to shading issues), but we no longer do.

Once 1.15.0, we should update the docs, too :)

**Comment by marcusphi** [comment]
https://github.com/testcontainers/testcontainers-java/issues/3295#issuecomment-702082805
I have same problem after upgrading to testcontainers 1.15.0. Time to update the docs now?

**Comment by adriancole** [comment]
any chance to revert or offer a shaded option? testcontainers is at the bottom of the classpath and it can be annoying if possible for everyone to work around docker-java's dependency tree.

**Comment by bsideup** [comment]
@adriancole it is not possible to revert (because it comes from `docker-java-api` that we no longer shade) but I will lower the Jackson dependency version in `docker-java` so that old projects won't fail due to it

**Comment by adriancole** [comment]
works for me, thanks!
