### ISSUE TITLE
[Bug]: ScriptUtils.runInitScript from database-commons 1.21.3 produces NoClassDefFoundError when upgrading testcontainers to 2.0.1

### ISSUE THREAD

**Issue by westernsam** [testcontainers/testcontainers-java#11135]
### Module

Core

### Testcontainers version

2.0.1

### Using the latest Testcontainers version?

Yes

### Host OS

linux

### Host Arch

x86

### Docker version

```shell
docker version
Client: Docker Engine - Community
 Version:           28.5.1
 API version:       1.51
 Go version:        go1.24.8
 Git commit:        e180ab8
 Built:             Wed Oct  8 12:17:26 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.5.1
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.8
  Git commit:       f8215cc
  Built:            Wed Oct  8 12:17:26 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.28
  GitCommit:        b98a3aace656320842a23f4a392a33f46af97866
 runc:
  Version:          1.3.0
  GitCommit:        v1.3.0-0-g4ca628d1
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

There is an issue using ScriptUtils.runInitScript from database-commons version 1.21.3 (the latest available version) after upgrading testcontainers to 2.0.1. It seems that apache commons has been removed from shaded in the latest version.

version.org.testcontainers..testcontainers=2.0.1

version.org.testcontainers..jdbc=1.21.3

### Relevant log output

```shell
java.lang.NoClassDefFoundError: org/testcontainers/shaded/org/apache/commons/io/IOUtils
	at org.testcontainers.ext.ScriptUtils.runInitScript(ScriptUtils.java:212)
	at PublicTimescaleResources.increaseEnergyDuringEvent(PublicTimescaleResources.kt:26)
	at endToEnd.BillingTest.can filter out negative event from bill(BillingTest.kt:854)
Caused by: java.lang.ClassNotFoundException: org.testcontainers.shaded.org.apache.commons.io.IOUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 3 more
```

**Comment by FunkyMuse** [comment]
Same here

**Comment by MRyves** [comment]
Same Here

**Comment by eddumelendez** [comment]
Make sure all your dependencies are using 2.0.1. See you are using different versions

```
version.org.testcontainers..testcontainers=2.0.1

version.org.testcontainers..jdbc=1.21.3
```

I have created an example with MySQLContainer and everything is working fine

```java
MySQLContainer mysql = new MySQLContainer("mysql:8.0.28")
                .withInitScript("init.sql")
```

Otherwise, please submit a project that reproduces the issue.

**Comment by westernsam** [comment]
I am using the latest published version of jdbc and database-commons 
https://mvnrepository.com/artifact/org.testcontainers/database-commons
https://mvnrepository.com/artifact/org.testcontainers/jdbc

$ ./gradlew update
> Task :test-persistence:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test-persistence:compileKotlin'.
> Could not resolve all files for configuration ':test-persistence:compileClasspath'.
   > Could not find org.testcontainers:jdbc:2.0.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/testcontainers/jdbc/2.0.1/jdbc-2.0.1.pom
     Required by:
         project :test-persistence

See attached minimal example

[testcontainers-issue-minimal-example.zip](https://github.com/user-attachments/files/23259203/testcontainers-issue-minimal-example.zip)

**Comment by FunkyMuse** [comment]
> I am using the latest published version of jdbc and database-commons https://mvnrepository.com/artifact/org.testcontainers/database-commons https://mvnrepository.com/artifact/org.testcontainers/jdbc
> 
> $ ./gradlew update
> 
> > Task :test-persistence:compileKotlin FAILED
> 
> FAILURE: Build failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':test-persistence:compileKotlin'.
> 
> 
> > Could not resolve all files for configuration ':test-persistence:compileClasspath'.
> > Could not find org.testcontainers:jdbc:2.0.1.
> > Searched in the following locations:
> > - https://repo.maven.apache.org/maven2/org/testcontainers/jdbc/2.0.1/jdbc-2.0.1.pom
> > Required by:
> > project :test-persistence
> 
> See attached minimal example
> 
> [testcontainers-issue-minimal-example.zip](https://github.com/user-attachments/files/23259203/testcontainers-issue-minimal-example.zip)

2.0.1 is not released @eddumelendez same issue here, can't find it for any other than the core container

**Comment by lobaorn-bitso** [comment]
Found it, it all now have `testcontainers-` prefix for some reason: https://mvnrepository.com/artifact/org.testcontainers/testcontainers-database-commons/2.0.1

Not sure if its intended.

**Comment by lobaorn-bitso** [comment]
Yes, it is intended, as per release docs: https://github.com/testcontainers/testcontainers-java/releases/tag/2.0.0

> All modules are now prefixed with testcontainers-. For example, org.testcontainers:mysql is now org.testcontainers:testcontainers-mysql

cc @westernsam @FunkyMuse @MRyves 

Lets just use the OpenRewrite recipe: https://docs.openrewrite.org/changelog/8-64-0-Release

**Comment by westernsam** [comment]
Thanks @lobaorn-bitso - that resolves my issue. Will remember to check release notes in future!
