### PR TITLE
Use reflection to circumvent api changes in Selenium 4

### LINKED ISSUE #4593: 1.16.1 fails for Selenium 4.0.0 and Chrome browser
I am using Selenium 4.0.0 with Chrome as web browser. When I upgrade testcontainers to 1.16.1 I get the following error:
```
java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chrome/ChromeOptions;
		at org.testcontainers.containers.BrowserWebDriverContainer.configure(BrowserWebDriverContainer.java:173)
		at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:322)
		at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
```

The error does not exist on 1.16.0.

### PR DESCRIPTION
**Pull request by tobiasstadler**
Fixes #4593

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@kiview What is your opinion to my approach?

**Comment by kiview** [comment]
Superseded by #4914.
